import React from "react";

const About = () => {
  return (
    <div className="flex flex-col">
      <div className="mb-4 mt-4">
        <h1 className="text-[36px] font-extrabold text-[#222328] font-inter">
          Welcome to <span className="text-red-400">IntelliMage</span>
        </h1>
        <div className="flex w-[1200px]">
          <p className="mt-2 text-[#666e75] text-[18px] max-w[500px]">
            We are an AI image generating website. The images generated on our
            website are generated by OpenAI's DALL-E. All the images are
            originals and can be used for personal purposes. This AI image
            generating website using DALL-E and OpenAI is a user-friendly
            platform where anyone can create unique and high-quality images
            based on natural language descriptions. The AI technology used on
            this website is state-of-the-art, allowing for the creation of
            realistic and imaginative images in a variety of categories and
            styles.
          </p>
        </div>
        <div className="mt-4 mb-4">
          <h1 className="text-[36px] font-extrabold text-[#222328] font-inter">
            Our Community
          </h1>
        </div>
      </div>
    </div>
  );
};

export default About;
